carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
#Importamos las vistas
from . import views
#Importación para url de archivos estáticos
from django.conf.urls.static import static
from django.conf import settings
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    #Para evitar que un ataque de algún hacker, modificamos el admin/ por securelogin/
    path('securelogin/', admin.site.urls),
    #Instalamos el módulo django-admin-honeypot para proporcionarle a posibles hackers una url del admin falsa
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    #Una url vacía lleva automáticamente al home
    path('', views.home, name='home'),
    #Las url de las aplicaciones son las sioguientes
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    #A continuación se incluyen las url para los archivos estáticos
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    #Creamos urls dinámicas con parámetros
    path('category/<slug:category_slug>/', views.store, name="products_by_category"),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_detail"),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.
#Clase para el carrito de compra
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


#Elemento o producto que se elige y agrega al carrito
class CartItem(models.Model):
    #Establecemos las relaciones con las tablas de usuario y producto
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    #Almacenamos las variaciones como color y talle en el carrito de compras
    variations = models.ManyToManyField(Variation, blank=True)

    #Establecemos las relaciones con la tabla carrito
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    #Devolvemos un subtotal sin impuestos (tax)
    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    #Unimos las dos tablas
    #Con on_delete=models.CASCADE liberamos un proceso en cascada cuando se elimina una categoría
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    #Hacemos la url dinamica que nos lleva al link del producto que queremos
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    #Función para obtener el promedio de las calificaciones de los productos
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    #Función para contar las cantidad de calificaciones que recibió un producto
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


#Con esta clase gestionamos las variaciones de productos para poder filtrarlas en el html
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def tallas(self):
        return super(VariationManager, self).filter(variation_category='talla', is_active=True)


#Diccionario para limitar las opciones posibles a elegir en variaciones
variation_category_choice = {
    ('color', 'color'),
    ('talla', 'talla'),
}
#Clase para crear y controlar las variaciones de los productos como tamaño y color
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    #Instanciamos a VariationManager para poder usarlo
    objects = VariationManager()

    def __str__(self):
        return self.variation_category + ': ' + self.variation_value

#Con esta clase podemos crear y almacenar la calificación y opinión de los usuarios sobre los productos
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    #Para el título del comentario
    subject = models.CharField(max_length=100, blank=True)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    #IP desde la cual se envía el puntaje
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
#Con esta librería controlamos el acceso al sitio si el usuario esta logueado o no
from django.contrib.auth.decorators import login_required

# Create your views here.

#Función privada para vincular el carrito a la sesión del usuario
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        #Se crea una nueva sesión si es que no existe
        cart = request.session.create()
    
    return cart

#Función para agregar a carrito
def add_cart(request, product_id):
    #Seleccionamos el producto a agregar por el id
    product = Product.objects.get(id=product_id)

    current_user = request.user
    if current_user.is_authenticated:
        #Lógica del carrito cuando el usuario esta autenticado
        product_variation = []

        if request.method == 'POST':#Si el método es POST, aplicamos un bucle para contar la cantidad de variaciones
            for item in request.POST:
                key = item #Capturamos el nombre o tipo de variación
                value = request.POST[key] #Capturamos el valor
                #Verificamos si la variacion existe en la base de datos
                try:
                    #Buscamos por producto y variación
                    variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact = value)
                    product_variation.append(variation)
                except:
                    pass

        #Cargamos el carrito según el usuario ya haya elegido productos con variaciones iguales o no
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)

            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity +=1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user = current_user)
                #Insertamos las variaciones al carrito de compras sólo si no están en blanco
                if len(product_variation) > 0:
                    item.variations.clear()#Limpiamos por las dudas que ya tenga valores
                    item.variations.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            #Insertamos las variaciones al carrito de compras sólo si no están en blanco
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

            cart_item.save()
        return redirect('cart')


    else:
        #Hacemos la cantidad de variaciones como talla o color sean dinámicas
        product_variation = []

        if request.method == 'POST':#Si el método es POST, aplicamos un bucle para contar la cantidad de variaciones
            for item in request.POST:
                key = item #Capturamos el nombre o tipo de variación
                value = request.POST[key] #Capturamos el valor
                #Verificamos si la variacion existe en la base de datos
                try:
                    #Buscamos por producto y variación
                    variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact = value)
                    product_variation.append(variation)
                except:
                    pass


        #Verificamos si el carrito existe o no con try para evitar que se trabe la aplicación
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            ) 
        cart.save()

        #Cargamos el carrito según el usuario ya haya elegido productos con variaciones iguales o no
        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)

            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity +=1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                #Insertamos las variaciones al carrito de compras sólo si no están en blanco
                if len(product_variation) > 0:
                    item.variations.clear()#Limpiamos por las dudas que ya tenga valores
                    item.variations.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            #Insertamos las variaciones al carrito de compras sólo si no están en blanco
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

            cart_item.save()
        return redirect('cart')

#Función para eliminar de carrito
def remove_cart(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)

    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user = request.user, id = cart_item_id)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

        if(cart_item.quantity) > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    
    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id = product_id)

    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user = request.user, id = cart_item_id)
    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

    cart_item.delete()
    return redirect('cart')

#Renderizamos store.html
def cart(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        #Con este for sabemos la cantidad de cada tipo de productos que hay en el carrito y el precio
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (21 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quentity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        #Con este for sabemos la cantidad de cada tipo de productos que hay en el carrito y el precio
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (21 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/checkout.html', context)

templates/store/product_detail.html
{% extends 'base.html' %}


{% block content %}

<section class="section-content padding-y bg">

  <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage">
           <center><img src="{{ single_product.image.url }}"></center>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
      <ul class="thumb">
        <li>
          <a href="{{single_product.image.url}}" target="mainImage">
            <img src="{{single_product.image.url}}" alt="Imagen del Producto">
          </a>
          
          {% for i in product_gallery %}
            <a href="{{i.image.url}}" target="mainImage">
              <img src="{{i.image.url}}" alt="Imagen del Producto">
            </a>
          {% endfor %}
            

        </li>
      </ul>
            </aside>
            <main class="col-md-6 border-left">

    <form action="{% url 'add_cart' single_product.id %}" method="POST">
      {% csrf_token %}
      <article class="content-body">
      
        <h2 class="title">{{ single_product.product_name }}</h2>
        <div class="rating-star">
          <span>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
          </span>
        </div>
        <span>{{ single_product.countReview }} Comentarios</span>
      
        <div class="mb-3"> 
          <var class="price h4">${{ single_product.price }}</var> 
        </div> 
      
        <p>{{ single_product.description }}</p>
      
      
          <hr>
          <div class="row">
            <div class="item-option-select">
              <h6>Seleccionar Color</h6>
              <select class="form-control" name="color" required>
                <option value="" disabled selected>Seleccione</option>
                {% for i in single_product.variation_set.colors %}
                  <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                {% endfor %}
              </select>
            </div>
          </div> <!-- row.// -->

          <div class="row">
            <div class="item-option-select">
              <h6>Seleccionar Tamaño</h6>
              <select class="form-control" name="talla" required>
                <option value="" disabled selected>Seleccione</option>
                {% for i in single_product.variation_set.tallas %}
                  <option value="{{i.variation_value | lower}}">{{i.variation_value | capfirst}}</option>
                {% endfor %}
              </select>
            </div>
          </div> <!-- row.// -->

            <hr>
            {% if single_product.stock <= 0 %}
              <h5>Producto fuera de stock</h5>
            {% else %}
            <button type="submit" class="btn btn-primary"><span class="text">Agregar al Carrito</span><i class="fas fa-shopping-cart"></i></button>
            {% endif %}

      </article> <!-- product-info-aside .// -->
    </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
      <div class="col-md-9">
        
        <!--Creamos el formulario-->
        <form action="{% url 'submit_review' single_product.id %}" method="post">
          {% csrf_token %}

          <h5>Escriba su comentario</h5>
          <div class="">
            <label for="">¿Cómo calificaría nuestro producto?</label>
            <br>
            <div class="rate">
              <!--Creamos el ranking de estrellas-->
              <input type="radio" name="rating" value="5" id="rating10"><label for="rating10" title="5"></label>
              <input type="radio" name="rating" value="4.5" id="rating9"><label for="rating9" title="4.5" class="half"></label>
              <input type="radio" name="rating" value="4" id="rating8"><label for="rating8" title="4"></label>
              <input type="radio" name="rating" value="3.5" id="rating7"><label for="rating7" title="3.5" class="half"></label>
              <input type="radio" name="rating" value="3" id="rating6"><label for="rating6" title="3"></label>
              <input type="radio" name="rating" value="2.5" id="rating5"><label for="rating5" title="2.5" class="half"></label>
              <input type="radio" name="rating" value="2" id="rating4"><label for="rating4" title="2"></label>
              <input type="radio" name="rating" value="1.5" id="rating3"><label for="rating3" title="1.5" class="half"></label>
              <input type="radio" name="rating" value="1" id="rating2"><label for="rating2" title="1"></label>
              <input type="radio" name="rating" value="0.5" id="rating1"><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>

            Título del comentario:
            <input type="text" class="form-control" name="subject" value="">
            <br>

            Comentario:
            <textarea class="form-control" name="review" rows="4" ></textarea>
            <br>

            <!--Condición para que el botón de 'Enviar' sólo le aparezca a los usuarios logueados-->
            {% if user.is_authenticated %}
              
              {% if orderproduct %}
              <input type="submit" class="btn btn-primary" name="" value="Enviar Comentario">
              {% else %}
              <p>Debe primero comprar el producto para poder enviar un comentario.</p>
              {% endif %}
                
              
            {% else %}
              <p>Para enviar un comentario debe estar registrado.<span><a href="{% url 'login' %}">Inicia Sesión</a></span></p>
            {% endif %}
            <!--Incluimos los mensajes de alerta--> 
            {% include 'includes/alerts.html' %}

          </div>

        </form>

        <header class="section-heading">
          <h3>Calificación de Clientes</h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
            </span>
          </div>

        </header>
        
        {% for review in reviews %}
          
        <article class="box mb-3">
          <div class="icontext w-100">
            <div class="text">
              <span class="date text-muted float-md-right">{{ review.updated_at }}</span>  
              <h6 class="mb-1">{{review.user.full_name}}</h6>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                </span>
              </div>
              
            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>{{ review.review }}</p>	
          </div>
        </article>

        {% endfor %}

      </div> <!-- col.// -->
    </div> <!-- row.// -->
    
  </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

    {% endblock content %}